name: R2Streamer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    env:
      scheme: ${{ 'r2-streamer-swift' }}
      platform: ${{ 'iOS Simulator' }}
      device: ${{ 'iPhone 13' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install xcodegen
      - name: Check Carthage project
        run: |
          # Check that the Carthage project is up to date.
          make carthage
          git diff --exit-code --name-only r2-streamer-swift.xcodeproj
      - name: Prepare build
        run: |
          # r2-streamer-swift.xcodeproj is only relevant for Carthage. We remove it otherwise xcodebuild will use it.
          rm -rf r2-streamer-swift.xcodeproj
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=$device"
